image: gradle:latest

build:
  stage: build
  script:
    - gradle assemble

test:
  stage: test
  script:
    - gradle allTests
  artifacts:
    paths:
      - build/reports/
    when: always


pages:
  stage: deploy
  script:
    - gradle dokka
    - mv build/docs public
  artifacts:
    paths:
      - public
  only:
    - master
