image: gradle:latest

cache: &global_cache
  # per-branch cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - gradle assemble --build-cache
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - gradle allTests
  artifacts:
    paths:
      - build/reports/
    when: always

publish:
  stage: deploy
  when: manual
  script:
    - gradle publish
  cache:
    # only pull global_cache
    <<: *global_cache
    policy: pull
  # use only artifacts from build job
  dependencies:
    - build

pages:
  stage: deploy
  script:
    - gradle dokka
    - mv build/docs public
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    # only pull global_cache
    <<: *global_cache
    policy: pull
  # use only artifacts from build job
  dependencies:
    - build
