image: gradle:latest

build:
  stage: build
  script:
    - gradle assemble

test:
  stage: test
  script:
    - gradle allTests


pages:
  stage: deploy
  script:
    - gradle dokka
    - cp -r build/docs public
    - ln -s c-crdtlib/index.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
