image: gradle:latest

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

cache: &global_cache
  # per-branch cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - pwd ; echo $CI_PROJECT_DIR ; ls -la ; ls -l .gradle
    - gradle assemble --build-cache --info
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - pwd ; echo $CI_PROJECT_DIR ; ls -la ; ls -l .gradle
    - gradle allTests --info
  artifacts:
    paths:
      - build/reports/
    when: always

publish:
  stage: deploy
  when: manual
  script:
    - gradle publish --info
  cache:
    # only pull global_cache
    <<: *global_cache
    policy: pull
  # use only artifacts from build job
  dependencies:
    - build

pages:
  stage: deploy
  script:
    - gradle dokka
    - mv build/docs public
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    # only pull global_cache
    <<: *global_cache
    policy: pull
  # use only artifacts from build job
  dependencies:
    - build
